import {requireUser,getPermissions} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";
import {tatDays,dateRange} from "@/lib/reporting";
export default async function Reporting({searchParams}:{searchParams:Promise<{from?:string;to?:string;group?:string}>}){
 const u=await requireUser();const perms=await getPermissions(u.id);if(!perms.has("reports.view"))return <div className="card p-6">Reporting permission required.</div>;
 const p=await searchParams;const from=p.from||"";const to=p.to||"";const group=["supplier_name","distributor_name","dealer_name","received_date_rnd"].includes(p.group||"")?p.group!:"supplier_name";
 const valid=dateRange(from,to);let rows:any[]=[];let error="";
 if(valid){const result=await createAdminClient().from("service_records").select("*").gte("received_date_rnd",from).lte("received_date_rnd",to).order("received_date_rnd").limit(5000);rows=result.data||[];error=result.error?.message||"";}
 const grouped=new Map<string,{count:number,closed:number,sum:number,withTat:number}>();
 for(const row of rows){const key=String(row[group]||"Unknown");const cur=grouped.get(key)||{count:0,closed:0,sum:0,withTat:0};cur.count++;if(row.current_status==="CLOSED")cur.closed++;const tat=tatDays(row);if(tat!==null){cur.sum+=tat;cur.withTat++;}grouped.set(key,cur);}
 const params=new URLSearchParams({from,to,group});
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Reporting</h1><p className="text-sm text-slate-500">Date range is based on Received Date at R&D; TAT is calendar days.</p></div>
 <form className="card grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><label>From date</label><input type="date" name="from" defaultValue={from} required/></div><div><label>To date</label><input type="date" name="to" defaultValue={to} required/></div><div><label>Presentation breakdown</label><select name="group" defaultValue={group}><option value="supplier_name">Supplier wise</option><option value="distributor_name">Distributor wise</option><option value="dealer_name">Dealer wise</option><option value="received_date_rnd">Date wise</option></select></div><button className="btn-primary self-end">Run reports</button></form>
 {!valid?<div className="card p-5 text-sm text-slate-500">Choose valid From and To dates to generate reports.</div>:error?<div className="card p-5 text-red-700">{error}</div>:<>
 <section className="card p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Detailed report</h2><p className="text-xs text-slate-500">Includes every record and related workflow activities in CSV download.</p></div><a className="btn-primary" href={`/api/reporting?${new URLSearchParams({from,to,type:"detailed"})}`}>Download detailed CSV</a></div><div className="text-sm">{rows.length} service records in selected range. The CSV includes milestones, documents metadata, logistics, status history and audit activities.</div></section>
 <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-lg font-semibold">Presentation report · TAT only</h2><p className="text-xs text-slate-500">Average calculated on completed cases with a closure date; open cases excluded from average.</p></div><a className="btn-primary" href={`/api/reporting?${new URLSearchParams({from,to,group,type:"presentation"})}`}>Download TAT CSV</a></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">{group.replaceAll("_"," ")}</th><th className="p-3">Records</th><th className="p-3">Closed</th><th className="p-3">With TAT</th><th className="p-3">Average TAT (days)</th></tr></thead><tbody>{[...grouped.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,g])=><tr key={name} className="border-t"><td className="p-3 font-semibold">{name}</td><td className="p-3">{g.count}</td><td className="p-3">{g.closed}</td><td className="p-3">{g.withTat}</td><td className="p-3">{g.withTat?(g.sum/g.withTat).toFixed(1):"—"}</td></tr>)}</tbody></table></div></section></>}
 </div>;
}
