import { requireUser, getPermissions } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
export default async function UsersPage(){
  const user=await requireUser(); const perms=await getPermissions(user.id); if(!perms.has("users.manage")) return <div className="card p-6">You do not have permission to manage users.</div>;
  const db=createAdminClient(); const [{data:profiles},{data:roles},{data:userRoles}]=await Promise.all([db.from("profiles").select("*").order("created_at",{ascending:false}),db.from("roles").select("*").order("name"),db.from("user_roles").select("user_id,role_id,roles(name)")]);
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Users</h1><p className="text-sm text-slate-500">Create accounts and assign one or more roles.</p></div>
  <form action="/api/admin/users" method="post" className="card grid gap-3 p-5 md:grid-cols-4"><input type="hidden" name="op" value="create"/><input name="full_name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Temporary password" minLength={8} required/><select name="role_id" required><option value="">Role</option>{(roles??[]).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="btn-primary md:col-span-4 md:w-fit">Create user</button></form>
  <div className="card overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Roles</th><th className="p-3">Active</th><th className="p-3">Add role</th></tr></thead><tbody>{(profiles??[]).map((p:any)=>{const assigned=(userRoles??[]).filter((x:any)=>x.user_id===p.id);return <tr key={p.id} className="border-t"><td className="p-3 font-medium">{p.full_name||"—"}</td><td className="p-3">{p.email}</td><td className="p-3"><div className="flex flex-wrap gap-1">{assigned.length?assigned.map((a:any)=><form key={a.role_id} action="/api/admin/users" method="post" className="inline-flex"><input type="hidden" name="op" value="remove_role"/><input type="hidden" name="user_id" value={p.id}/><input type="hidden" name="role_id" value={a.role_id}/><button className="rounded-full bg-slate-100 px-2 py-1 text-xs" title="Remove role">{a.roles?.name} ×</button></form>):"—"}</div></td><td className="p-3"><form action="/api/admin/users" method="post"><input type="hidden" name="op" value="toggle_active"/><input type="hidden" name="user_id" value={p.id}/><input type="hidden" name="is_active" value={p.is_active?"false":"true"}/><button className="btn-secondary">{p.is_active?"Deactivate":"Activate"}</button></form></td><td className="p-3"><form action="/api/admin/users" method="post" className="flex gap-2"><input type="hidden" name="op" value="assign_role"/><input type="hidden" name="user_id" value={p.id}/><select name="role_id" required className="max-w-40"><option value="">Select</option>{(roles??[]).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="btn-secondary">Assign</button></form></td></tr>})}</tbody></table></div></div>
}
